In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("/Users/masonwang/Documents/Code/MNIST OCR ML/OCR-for-MNIST/data/mnist_test.csv")
data = np.array(data)
m, n = data.shape

In [4]:
test_data = data[0:1000].T
test_y = test_data[0]
test_x = test_data[1:n]

In [5]:
training_data = data[1000:m].T
training_y = training_data[0]
training_x = training_data[1:n]

In [10]:
print(training_y)
print(training_x)

[9 0 2 ... 4 5 6]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
